
title: Yangang Yao's Homepage
page-top-title: Yangang Yao (姚焱刚)
top-section-bg-text: An LLM Designer and Efficient Machine Learning System Nerd
home-subtitle: Yangang Yao&ensp;|&ensp;姚焱刚
copyright-text: '&copy; Yangang Yao 2024. All Rights Reserved.'
